server:
  port: 8084
  address: 0.0.0.0

spring:
  application:
    name: persephone
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:h2:file:/data/persephone
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: true
    url: jdbc:h2:file:/data/persephone
    user: sa
    password:
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
