server:
  port: 8084

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  application:
    name: persephone
  devtools:
    restart:
      enabled: false
  liquibase:
    enabled: true
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.apache.coyote.http11: ERROR
