server:
  port: 8084

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  application:
    name: persephone
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.sqlite.JDBC
  liquibase:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.apache.coyote.http11: ERROR
