server:
  port: 8084

spring:
  application:
    name: persephone
  devtools:
    restart:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email, openid
  datasource:
    url: jdbc:h2:file:/data/persephone
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: true
    url: jdbc:h2:file:/data/persephone
    user: sa
    password:
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    root: INFO
