cors:
  allowed-origins: http://localhost:5173, chrome-extension://fgponpodhbmadfljofbimhhlengambbn

spring:
  datasource:
    url: jdbc:h2:file:/data/persephone
    username: sa
    password:
  liquibase:
    url: jdbc:h2:file:/data/persephone
    user: sa
    password:
